export const FORMATION_CATEGORIES: string[] = [
  "Langues",
  "Informatique",
  "Création d'Applications Web",
  "Téléphonie",
  "Dépannage Informatique",
  "Maintenance Informatique",
  "Freelance",
  "Crypto Monnaies",
  "Rédaction Web",
  "Cuisine",
  "Boulangerie",
  "Pâtisserie",
  "Facebook Marketing",
  "Développement Personnel",
  "Management",
  "Auto-École",
  "Importation de Produits",
  "Commerce",
  "Marketing Digital",
  "Cours Bacc et BEPC",
  "Cours Universitaire",
  "Cours Primaire",
  "Cours Secondaire",
  "Montage Vidéo",
  "Musique",
  "Couture",
  "Coiffure",
  "Installation Réseau",
  "Création de Comptes Professionnels",
  "Kabary et Communication",
  "Construction et Bâtiment",
  "Sports",
  "Coaching",
  "Beauté",
  "Décoration Florale",
  "Community Manager",
  "Exportation",
  "Entreprise",
  "Transit et Douane",
  "Télétravail",
  "Logistique et transport",
  "Trading",
  "Gestion financière",
  "Élevage et Agriculture",
  "Pisciculture",
  "Secrétariat Médical",
  "Conseils Financiers",
  "Business Plan",
  "Consulting en Affaires",
  "Savonnerie et Huiles",
  "Huile essentielle et Alcool",
  "Conseils Business",
  "Conseils Conjugaux",
  "Autres Formations",
];

export const CERTIFICATE_TYPES = [
  { value: "formation_simple", label: "Formation simple" },
  { value: "certificat_national", label: "Certificat National" },
  { value: "certificat_international", label: "Certificat International" },
  { value: "equivalence_diplome", label: "Équivalence Diplôme" },
  { value: "diplome", label: "Diplôme" },
];
