/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedPaiementsRouteImport } from './routes/_authenticated/paiements'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMesModulesRouteImport } from './routes/_authenticated/mes-modules'
import { Route as AuthenticatedAffiliationRouteImport } from './routes/_authenticated/affiliation'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedFormationsIndexRouteImport } from './routes/_authenticated/formations.index'
import { Route as AuthenticatedModulesIdRouteImport } from './routes/_authenticated/modules.$id'
import { Route as AuthenticatedFormationsIdRouteImport } from './routes/_authenticated/formations.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaiementsRoute = AuthenticatedPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMesModulesRoute = AuthenticatedMesModulesRouteImport.update({
  id: '/mes-modules',
  path: '/mes-modules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAffiliationRoute =
  AuthenticatedAffiliationRouteImport.update({
    id: '/affiliation',
    path: '/affiliation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFormationsIndexRoute =
  AuthenticatedFormationsIndexRouteImport.update({
    id: '/formations/',
    path: '/formations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulesIdRoute = AuthenticatedModulesIdRouteImport.update({
  id: '/modules/$id',
  path: '/modules/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFormationsIdRoute =
  AuthenticatedFormationsIdRouteImport.update({
    id: '/formations/$id',
    path: '/formations/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/affiliation': typeof AuthenticatedAffiliationRoute
  '/mes-modules': typeof AuthenticatedMesModulesRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/paiements': typeof AuthenticatedPaiementsRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/formations/$id': typeof AuthenticatedFormationsIdRoute
  '/modules/$id': typeof AuthenticatedModulesIdRoute
  '/formations/': typeof AuthenticatedFormationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/affiliation': typeof AuthenticatedAffiliationRoute
  '/mes-modules': typeof AuthenticatedMesModulesRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/paiements': typeof AuthenticatedPaiementsRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/formations/$id': typeof AuthenticatedFormationsIdRoute
  '/modules/$id': typeof AuthenticatedModulesIdRoute
  '/formations': typeof AuthenticatedFormationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/affiliation': typeof AuthenticatedAffiliationRoute
  '/_authenticated/mes-modules': typeof AuthenticatedMesModulesRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/paiements': typeof AuthenticatedPaiementsRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/formations/$id': typeof AuthenticatedFormationsIdRoute
  '/_authenticated/modules/$id': typeof AuthenticatedModulesIdRoute
  '/_authenticated/formations/': typeof AuthenticatedFormationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/affiliation'
    | '/mes-modules'
    | '/messages'
    | '/notifications'
    | '/paiements'
    | '/profil'
    | '/formations/$id'
    | '/modules/$id'
    | '/formations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/affiliation'
    | '/mes-modules'
    | '/messages'
    | '/notifications'
    | '/paiements'
    | '/profil'
    | '/formations/$id'
    | '/modules/$id'
    | '/formations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/affiliation'
    | '/_authenticated/mes-modules'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/paiements'
    | '/_authenticated/profil'
    | '/_authenticated/formations/$id'
    | '/_authenticated/modules/$id'
    | '/_authenticated/formations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paiements': {
      id: '/_authenticated/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof AuthenticatedPaiementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mes-modules': {
      id: '/_authenticated/mes-modules'
      path: '/mes-modules'
      fullPath: '/mes-modules'
      preLoaderRoute: typeof AuthenticatedMesModulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/affiliation': {
      id: '/_authenticated/affiliation'
      path: '/affiliation'
      fullPath: '/affiliation'
      preLoaderRoute: typeof AuthenticatedAffiliationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formations/': {
      id: '/_authenticated/formations/'
      path: '/formations'
      fullPath: '/formations/'
      preLoaderRoute: typeof AuthenticatedFormationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules/$id': {
      id: '/_authenticated/modules/$id'
      path: '/modules/$id'
      fullPath: '/modules/$id'
      preLoaderRoute: typeof AuthenticatedModulesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formations/$id': {
      id: '/_authenticated/formations/$id'
      path: '/formations/$id'
      fullPath: '/formations/$id'
      preLoaderRoute: typeof AuthenticatedFormationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAffiliationRoute: typeof AuthenticatedAffiliationRoute
  AuthenticatedMesModulesRoute: typeof AuthenticatedMesModulesRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPaiementsRoute: typeof AuthenticatedPaiementsRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedFormationsIdRoute: typeof AuthenticatedFormationsIdRoute
  AuthenticatedModulesIdRoute: typeof AuthenticatedModulesIdRoute
  AuthenticatedFormationsIndexRoute: typeof AuthenticatedFormationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAffiliationRoute: AuthenticatedAffiliationRoute,
  AuthenticatedMesModulesRoute: AuthenticatedMesModulesRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPaiementsRoute: AuthenticatedPaiementsRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedFormationsIdRoute: AuthenticatedFormationsIdRoute,
  AuthenticatedModulesIdRoute: AuthenticatedModulesIdRoute,
  AuthenticatedFormationsIndexRoute: AuthenticatedFormationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
