/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAffiliationRouteImport } from './routes/_authenticated/affiliation'
import { Route as AuthenticatedMesModulesRouteImport } from './routes/_authenticated/mes-modules'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedPaiementsRouteImport } from './routes/_authenticated/paiements'
import { Route as AuthenticatedPartenaireRouteImport } from './routes/_authenticated/partenaire'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'
import { Route as AuthenticatedCategoriesIndexRouteImport } from './routes/_authenticated/categories.index'
import { Route as AuthenticatedCategoriesSlugRouteImport } from './routes/_authenticated/categories.$slug'
import { Route as AuthenticatedEcolesIdRouteImport } from './routes/_authenticated/ecoles.$id'
import { Route as AuthenticatedFormationsIndexRouteImport } from './routes/_authenticated/formations.index'
import { Route as AuthenticatedFormationsIdRouteImport } from './routes/_authenticated/formations.$id'
import { Route as AuthenticatedModulesIdRouteImport } from './routes/_authenticated/modules.$id'
import { Route as AuthenticatedPartenaireIndexRouteImport } from './routes/_authenticated/partenaire.index'
import { Route as AuthenticatedPartenaireDureesRouteImport } from './routes/_authenticated/partenaire.durees'
import { Route as AuthenticatedPartenaireEcolesRouteImport } from './routes/_authenticated/partenaire.ecoles'
import { Route as AuthenticatedPartenaireFormationsRouteImport } from './routes/_authenticated/partenaire.formations'
import { Route as AuthenticatedPartenaireMessagesRouteImport } from './routes/_authenticated/partenaire.messages'
import { Route as AuthenticatedPartenaireModulesRouteImport } from './routes/_authenticated/partenaire.modules'
import { Route as AuthenticatedPartenaireTracksRouteImport } from './routes/_authenticated/partenaire.tracks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAffiliationRoute =
  AuthenticatedAffiliationRouteImport.update({
    id: '/affiliation',
    path: '/affiliation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMesModulesRoute = AuthenticatedMesModulesRouteImport.update({
  id: '/mes-modules',
  path: '/mes-modules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaiementsRoute = AuthenticatedPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartenaireRoute = AuthenticatedPartenaireRouteImport.update({
  id: '/partenaire',
  path: '/partenaire',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCategoriesIndexRoute =
  AuthenticatedCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCategoriesSlugRoute =
  AuthenticatedCategoriesSlugRouteImport.update({
    id: '/categories/$slug',
    path: '/categories/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEcolesIdRoute = AuthenticatedEcolesIdRouteImport.update({
  id: '/ecoles/$id',
  path: '/ecoles/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFormationsIndexRoute =
  AuthenticatedFormationsIndexRouteImport.update({
    id: '/formations/',
    path: '/formations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormationsIdRoute =
  AuthenticatedFormationsIdRouteImport.update({
    id: '/formations/$id',
    path: '/formations/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulesIdRoute = AuthenticatedModulesIdRouteImport.update({
  id: '/modules/$id',
  path: '/modules/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartenaireIndexRoute =
  AuthenticatedPartenaireIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPartenaireRoute,
  } as any)
const AuthenticatedPartenaireDureesRoute =
  AuthenticatedPartenaireDureesRouteImport.update({
    id: '/durees',
    path: '/durees',
    getParentRoute: () => AuthenticatedPartenaireRoute,
  } as any)
const AuthenticatedPartenaireEcolesRoute =
  AuthenticatedPartenaireEcolesRouteImport.update({
    id: '/ecoles',
    path: '/ecoles',
    getParentRoute: () => AuthenticatedPartenaireRoute,
  } as any)
const AuthenticatedPartenaireFormationsRoute =
  AuthenticatedPartenaireFormationsRouteImport.update({
    id: '/formations',
    path: '/formations',
    getParentRoute: () => AuthenticatedPartenaireRoute,
  } as any)
const AuthenticatedPartenaireMessagesRoute =
  AuthenticatedPartenaireMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedPartenaireRoute,
  } as any)
const AuthenticatedPartenaireModulesRoute =
  AuthenticatedPartenaireModulesRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => AuthenticatedPartenaireRoute,
  } as any)
const AuthenticatedPartenaireTracksRoute =
  AuthenticatedPartenaireTracksRouteImport.update({
    id: '/tracks',
    path: '/tracks',
    getParentRoute: () => AuthenticatedPartenaireRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/affiliation': typeof AuthenticatedAffiliationRoute
  '/mes-modules': typeof AuthenticatedMesModulesRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/paiements': typeof AuthenticatedPaiementsRoute
  '/partenaire': typeof AuthenticatedPartenaireRouteWithChildren
  '/profil': typeof AuthenticatedProfilRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/categories/$slug': typeof AuthenticatedCategoriesSlugRoute
  '/ecoles/$id': typeof AuthenticatedEcolesIdRoute
  '/formations/$id': typeof AuthenticatedFormationsIdRoute
  '/modules/$id': typeof AuthenticatedModulesIdRoute
  '/partenaire/durees': typeof AuthenticatedPartenaireDureesRoute
  '/partenaire/ecoles': typeof AuthenticatedPartenaireEcolesRoute
  '/partenaire/formations': typeof AuthenticatedPartenaireFormationsRoute
  '/partenaire/messages': typeof AuthenticatedPartenaireMessagesRoute
  '/partenaire/modules': typeof AuthenticatedPartenaireModulesRoute
  '/partenaire/tracks': typeof AuthenticatedPartenaireTracksRoute
  '/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/formations/': typeof AuthenticatedFormationsIndexRoute
  '/partenaire/': typeof AuthenticatedPartenaireIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/affiliation': typeof AuthenticatedAffiliationRoute
  '/mes-modules': typeof AuthenticatedMesModulesRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/paiements': typeof AuthenticatedPaiementsRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/categories/$slug': typeof AuthenticatedCategoriesSlugRoute
  '/ecoles/$id': typeof AuthenticatedEcolesIdRoute
  '/formations/$id': typeof AuthenticatedFormationsIdRoute
  '/modules/$id': typeof AuthenticatedModulesIdRoute
  '/partenaire/durees': typeof AuthenticatedPartenaireDureesRoute
  '/partenaire/ecoles': typeof AuthenticatedPartenaireEcolesRoute
  '/partenaire/formations': typeof AuthenticatedPartenaireFormationsRoute
  '/partenaire/messages': typeof AuthenticatedPartenaireMessagesRoute
  '/partenaire/modules': typeof AuthenticatedPartenaireModulesRoute
  '/partenaire/tracks': typeof AuthenticatedPartenaireTracksRoute
  '/categories': typeof AuthenticatedCategoriesIndexRoute
  '/formations': typeof AuthenticatedFormationsIndexRoute
  '/partenaire': typeof AuthenticatedPartenaireIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/affiliation': typeof AuthenticatedAffiliationRoute
  '/_authenticated/mes-modules': typeof AuthenticatedMesModulesRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/paiements': typeof AuthenticatedPaiementsRoute
  '/_authenticated/partenaire': typeof AuthenticatedPartenaireRouteWithChildren
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/auth_/callback': typeof AuthCallbackRoute
  '/_authenticated/categories/$slug': typeof AuthenticatedCategoriesSlugRoute
  '/_authenticated/ecoles/$id': typeof AuthenticatedEcolesIdRoute
  '/_authenticated/formations/$id': typeof AuthenticatedFormationsIdRoute
  '/_authenticated/modules/$id': typeof AuthenticatedModulesIdRoute
  '/_authenticated/partenaire/durees': typeof AuthenticatedPartenaireDureesRoute
  '/_authenticated/partenaire/ecoles': typeof AuthenticatedPartenaireEcolesRoute
  '/_authenticated/partenaire/formations': typeof AuthenticatedPartenaireFormationsRoute
  '/_authenticated/partenaire/messages': typeof AuthenticatedPartenaireMessagesRoute
  '/_authenticated/partenaire/modules': typeof AuthenticatedPartenaireModulesRoute
  '/_authenticated/partenaire/tracks': typeof AuthenticatedPartenaireTracksRoute
  '/_authenticated/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/_authenticated/formations/': typeof AuthenticatedFormationsIndexRoute
  '/_authenticated/partenaire/': typeof AuthenticatedPartenaireIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/affiliation'
    | '/mes-modules'
    | '/messages'
    | '/notifications'
    | '/paiements'
    | '/partenaire'
    | '/profil'
    | '/auth/callback'
    | '/categories/$slug'
    | '/ecoles/$id'
    | '/formations/$id'
    | '/modules/$id'
    | '/partenaire/durees'
    | '/partenaire/ecoles'
    | '/partenaire/formations'
    | '/partenaire/messages'
    | '/partenaire/modules'
    | '/partenaire/tracks'
    | '/categories/'
    | '/formations/'
    | '/partenaire/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/affiliation'
    | '/mes-modules'
    | '/messages'
    | '/notifications'
    | '/paiements'
    | '/profil'
    | '/auth/callback'
    | '/categories/$slug'
    | '/ecoles/$id'
    | '/formations/$id'
    | '/modules/$id'
    | '/partenaire/durees'
    | '/partenaire/ecoles'
    | '/partenaire/formations'
    | '/partenaire/messages'
    | '/partenaire/modules'
    | '/partenaire/tracks'
    | '/categories'
    | '/formations'
    | '/partenaire'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/affiliation'
    | '/_authenticated/mes-modules'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/paiements'
    | '/_authenticated/partenaire'
    | '/_authenticated/profil'
    | '/auth_/callback'
    | '/_authenticated/categories/$slug'
    | '/_authenticated/ecoles/$id'
    | '/_authenticated/formations/$id'
    | '/_authenticated/modules/$id'
    | '/_authenticated/partenaire/durees'
    | '/_authenticated/partenaire/ecoles'
    | '/_authenticated/partenaire/formations'
    | '/_authenticated/partenaire/messages'
    | '/_authenticated/partenaire/modules'
    | '/_authenticated/partenaire/tracks'
    | '/_authenticated/categories/'
    | '/_authenticated/formations/'
    | '/_authenticated/partenaire/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/affiliation': {
      id: '/_authenticated/affiliation'
      path: '/affiliation'
      fullPath: '/affiliation'
      preLoaderRoute: typeof AuthenticatedAffiliationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mes-modules': {
      id: '/_authenticated/mes-modules'
      path: '/mes-modules'
      fullPath: '/mes-modules'
      preLoaderRoute: typeof AuthenticatedMesModulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paiements': {
      id: '/_authenticated/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof AuthenticatedPaiementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partenaire': {
      id: '/_authenticated/partenaire'
      path: '/partenaire'
      fullPath: '/partenaire'
      preLoaderRoute: typeof AuthenticatedPartenaireRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/categories/': {
      id: '/_authenticated/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AuthenticatedCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories/$slug': {
      id: '/_authenticated/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof AuthenticatedCategoriesSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ecoles/$id': {
      id: '/_authenticated/ecoles/$id'
      path: '/ecoles/$id'
      fullPath: '/ecoles/$id'
      preLoaderRoute: typeof AuthenticatedEcolesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formations/': {
      id: '/_authenticated/formations/'
      path: '/formations'
      fullPath: '/formations/'
      preLoaderRoute: typeof AuthenticatedFormationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formations/$id': {
      id: '/_authenticated/formations/$id'
      path: '/formations/$id'
      fullPath: '/formations/$id'
      preLoaderRoute: typeof AuthenticatedFormationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules/$id': {
      id: '/_authenticated/modules/$id'
      path: '/modules/$id'
      fullPath: '/modules/$id'
      preLoaderRoute: typeof AuthenticatedModulesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partenaire/': {
      id: '/_authenticated/partenaire/'
      path: '/'
      fullPath: '/partenaire/'
      preLoaderRoute: typeof AuthenticatedPartenaireIndexRouteImport
      parentRoute: typeof AuthenticatedPartenaireRoute
    }
    '/_authenticated/partenaire/durees': {
      id: '/_authenticated/partenaire/durees'
      path: '/durees'
      fullPath: '/partenaire/durees'
      preLoaderRoute: typeof AuthenticatedPartenaireDureesRouteImport
      parentRoute: typeof AuthenticatedPartenaireRoute
    }
    '/_authenticated/partenaire/ecoles': {
      id: '/_authenticated/partenaire/ecoles'
      path: '/ecoles'
      fullPath: '/partenaire/ecoles'
      preLoaderRoute: typeof AuthenticatedPartenaireEcolesRouteImport
      parentRoute: typeof AuthenticatedPartenaireRoute
    }
    '/_authenticated/partenaire/formations': {
      id: '/_authenticated/partenaire/formations'
      path: '/formations'
      fullPath: '/partenaire/formations'
      preLoaderRoute: typeof AuthenticatedPartenaireFormationsRouteImport
      parentRoute: typeof AuthenticatedPartenaireRoute
    }
    '/_authenticated/partenaire/messages': {
      id: '/_authenticated/partenaire/messages'
      path: '/messages'
      fullPath: '/partenaire/messages'
      preLoaderRoute: typeof AuthenticatedPartenaireMessagesRouteImport
      parentRoute: typeof AuthenticatedPartenaireRoute
    }
    '/_authenticated/partenaire/modules': {
      id: '/_authenticated/partenaire/modules'
      path: '/modules'
      fullPath: '/partenaire/modules'
      preLoaderRoute: typeof AuthenticatedPartenaireModulesRouteImport
      parentRoute: typeof AuthenticatedPartenaireRoute
    }
    '/_authenticated/partenaire/tracks': {
      id: '/_authenticated/partenaire/tracks'
      path: '/tracks'
      fullPath: '/partenaire/tracks'
      preLoaderRoute: typeof AuthenticatedPartenaireTracksRouteImport
      parentRoute: typeof AuthenticatedPartenaireRoute
    }
  }
}

interface AuthenticatedPartenaireRouteChildren {
  AuthenticatedPartenaireDureesRoute: typeof AuthenticatedPartenaireDureesRoute
  AuthenticatedPartenaireEcolesRoute: typeof AuthenticatedPartenaireEcolesRoute
  AuthenticatedPartenaireFormationsRoute: typeof AuthenticatedPartenaireFormationsRoute
  AuthenticatedPartenaireMessagesRoute: typeof AuthenticatedPartenaireMessagesRoute
  AuthenticatedPartenaireModulesRoute: typeof AuthenticatedPartenaireModulesRoute
  AuthenticatedPartenaireTracksRoute: typeof AuthenticatedPartenaireTracksRoute
  AuthenticatedPartenaireIndexRoute: typeof AuthenticatedPartenaireIndexRoute
}

const AuthenticatedPartenaireRouteChildren: AuthenticatedPartenaireRouteChildren =
  {
    AuthenticatedPartenaireDureesRoute: AuthenticatedPartenaireDureesRoute,
    AuthenticatedPartenaireEcolesRoute: AuthenticatedPartenaireEcolesRoute,
    AuthenticatedPartenaireFormationsRoute:
      AuthenticatedPartenaireFormationsRoute,
    AuthenticatedPartenaireMessagesRoute: AuthenticatedPartenaireMessagesRoute,
    AuthenticatedPartenaireModulesRoute: AuthenticatedPartenaireModulesRoute,
    AuthenticatedPartenaireTracksRoute: AuthenticatedPartenaireTracksRoute,
    AuthenticatedPartenaireIndexRoute: AuthenticatedPartenaireIndexRoute,
  }

const AuthenticatedPartenaireRouteWithChildren =
  AuthenticatedPartenaireRoute._addFileChildren(
    AuthenticatedPartenaireRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAffiliationRoute: typeof AuthenticatedAffiliationRoute
  AuthenticatedMesModulesRoute: typeof AuthenticatedMesModulesRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPaiementsRoute: typeof AuthenticatedPaiementsRoute
  AuthenticatedPartenaireRoute: typeof AuthenticatedPartenaireRouteWithChildren
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedCategoriesSlugRoute: typeof AuthenticatedCategoriesSlugRoute
  AuthenticatedEcolesIdRoute: typeof AuthenticatedEcolesIdRoute
  AuthenticatedFormationsIdRoute: typeof AuthenticatedFormationsIdRoute
  AuthenticatedModulesIdRoute: typeof AuthenticatedModulesIdRoute
  AuthenticatedCategoriesIndexRoute: typeof AuthenticatedCategoriesIndexRoute
  AuthenticatedFormationsIndexRoute: typeof AuthenticatedFormationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAffiliationRoute: AuthenticatedAffiliationRoute,
  AuthenticatedMesModulesRoute: AuthenticatedMesModulesRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPaiementsRoute: AuthenticatedPaiementsRoute,
  AuthenticatedPartenaireRoute: AuthenticatedPartenaireRouteWithChildren,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedCategoriesSlugRoute: AuthenticatedCategoriesSlugRoute,
  AuthenticatedEcolesIdRoute: AuthenticatedEcolesIdRoute,
  AuthenticatedFormationsIdRoute: AuthenticatedFormationsIdRoute,
  AuthenticatedModulesIdRoute: AuthenticatedModulesIdRoute,
  AuthenticatedCategoriesIndexRoute: AuthenticatedCategoriesIndexRoute,
  AuthenticatedFormationsIndexRoute: AuthenticatedFormationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
